/*
 * File: app/store/MenuArrayStore.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MEC_App.store.MenuArrayStore', {
    extend: 'Ext.data.Store',

    requires: [
        'MEC_App.model.MenuModel',
        'MEC_App.store.override.MenuArrayStore',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Array'
    ],

    config: {
        data: [
            {
                ItemName: 'ut',
                ItemView: 'nihil',
                ItemIconURL: 'http//:delectus.ca/dolorem/quos/quo.asmx'
            },
            {
                ItemName: 'non',
                ItemView: 'maiores',
                ItemIconURL: 'https//:nam.info/nemo/beatae/autem'
            },
            {
                ItemName: 'nobis',
                ItemView: 'fuga',
                ItemIconURL: 'http//:dolores.net/facilis'
            },
            {
                ItemName: 'qui',
                ItemView: 'sint',
                ItemIconURL: 'http//:ut.biz/ut/fugiat.html'
            },
            {
                ItemName: 'dolorum',
                ItemView: 'vel',
                ItemIconURL: 'https//:velit.io/libero/corrupti/placeat'
            },
            {
                ItemName: 'delectus',
                ItemView: 'sit',
                ItemIconURL: 'https//:explicabo.io/reiciendis/et/laborum.asmx'
            },
            {
                ItemName: 'sed',
                ItemView: 'sapiente',
                ItemIconURL: 'https//:ut.me/dignissimos/esse/rerum'
            },
            {
                ItemName: 'sint',
                ItemView: 'itaque',
                ItemIconURL: 'http//:asperiores.me'
            },
            {
                ItemName: 'ab',
                ItemView: 'quod',
                ItemIconURL: 'http//:dolor.io/deserunt/facilis'
            }
        ],
        model: 'MEC_App.model.MenuModel',
        storeId: 'MenuArrayStore',
        proxy: {
            type: 'ajax',
            reader: {
                type: 'array'
            }
        }
    }
});