/*
 * File: app/store/MinistryNewsStore.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MEC_App.store.MinistryNewsStore', {
    extend: 'Ext.data.Store',

    requires: [
        'MEC_App.model.MinistryNewsModel',
        'MEC_App.store.override.MinistryNewsStore',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Array'
    ],

    config: {
        data: [
            {
                NewsTitle: 'Cumque In Blanditiis Omnis',
                NewsDate: '11/14/2002',
                NewsBrief: 'ad',
                NewsDetails: 'Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima. Eodem modo typi, qui nunc nobis videntur parum clari, fiant sollemnes in futurum.',
                NewsID: 82,
                NewsImgUrl: 'http//:eveniet.io/sit/voluptatem/quo'
            },
            {
                NewsTitle: 'Veritatis Illo Repudiandae Dolorum',
                NewsDate: '1/22/2008',
                NewsBrief: 'rerum',
                NewsDetails: 'Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.',
                NewsID: 2,
                NewsImgUrl: 'http//:atque.net/provident/enim.py'
            },
            {
                NewsTitle: 'Ut Amet Veritatis Ab Occaecati',
                NewsDate: '2/7/2001',
                NewsBrief: 'illo',
                NewsDetails: 'Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum.',
                NewsID: 688,
                NewsImgUrl: 'https//:eos.net/vel'
            },
            {
                NewsTitle: 'Est Est Dolore Aspernatur Cupiditate',
                NewsDate: '7/7/2006',
                NewsBrief: 'est',
                NewsDetails: 'Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.',
                NewsID: 774,
                NewsImgUrl: 'https//:qui.us/molestias/quasi'
            },
            {
                NewsTitle: 'In Fuga Qui',
                NewsDate: '4/1/2006',
                NewsBrief: 'est',
                NewsDetails: 'Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.',
                NewsID: 964,
                NewsImgUrl: 'https//:et.biz/esse.asp'
            },
            {
                NewsTitle: 'Eos Sint Molestias',
                NewsDate: '10/19/2007',
                NewsBrief: 'et',
                NewsDetails: 'Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius.',
                NewsID: 539,
                NewsImgUrl: 'http//:maxime.tv/sunt/deserunt.xml'
            },
            {
                NewsTitle: 'In Impedit Officia',
                NewsDate: '11/7/2003',
                NewsBrief: 'unde',
                NewsDetails: 'Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima. Eodem modo typi, qui nunc nobis videntur parum clari, fiant sollemnes in futurum. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima.',
                NewsID: 297,
                NewsImgUrl: 'https//:qui.net'
            },
            {
                NewsTitle: 'Nostrum Magni Vel Et Officia',
                NewsDate: '12/26/2001',
                NewsBrief: 'rem',
                NewsDetails: 'Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima.',
                NewsID: 192,
                NewsImgUrl: 'http//:explicabo.biz'
            },
            {
                NewsTitle: 'Esse Accusamus Nemo Aut Quis',
                NewsDate: '5/8/2009',
                NewsBrief: 'voluptatem',
                NewsDetails: 'Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima. Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Eodem modo typi, qui nunc nobis videntur parum clari, fiant sollemnes in futurum. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum.',
                NewsID: 890,
                NewsImgUrl: 'http//:ea.tv/in/doloribus/quo.php'
            },
            {
                NewsTitle: 'Ut Necessitatibus Porro',
                NewsDate: '2/4/2004',
                NewsBrief: 'corrupti',
                NewsDetails: 'Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum.',
                NewsID: 696,
                NewsImgUrl: 'http//:sint.org/aut/et/vel.xml'
            },
            {
                NewsTitle: 'Et Consequatur',
                NewsDate: '9/19/2013',
                NewsBrief: 'accusamus',
                NewsDetails: 'Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Eodem modo typi, qui nunc nobis videntur parum clari, fiant sollemnes in futurum.',
                NewsID: 744,
                NewsImgUrl: 'http//:molestias.us/ad/qui/facilis'
            },
            {
                NewsTitle: 'Quis Ea',
                NewsDate: '8/23/2008',
                NewsBrief: 'in',
                NewsDetails: 'Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Eodem modo typi, qui nunc nobis videntur parum clari, fiant sollemnes in futurum. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum.',
                NewsID: 798,
                NewsImgUrl: 'http//:ducimus.org/non/sed.jsp'
            },
            {
                NewsTitle: 'Repellat Aliquid Rem Doloremque',
                NewsDate: '2/15/2002',
                NewsBrief: 'impedit',
                NewsDetails: 'Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius.',
                NewsID: 35,
                NewsImgUrl: 'http//:sint.info/voluptatibus/ipsa.jsp'
            },
            {
                NewsTitle: 'Voluptas Quisquam Esse',
                NewsDate: '4/2/2005',
                NewsBrief: 'quis',
                NewsDetails: 'Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.',
                NewsID: 730,
                NewsImgUrl: 'http//:laboriosam.com'
            },
            {
                NewsTitle: 'Vitae Quis Quia Illo',
                NewsDate: '10/17/2014',
                NewsBrief: 'velit',
                NewsDetails: 'Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem.',
                NewsID: 319,
                NewsImgUrl: 'https//:eum.biz/ut/impedit.pl'
            }
        ],
        model: 'MEC_App.model.MinistryNewsModel',
        storeId: 'MinistryNewsStore',
        proxy: {
            type: 'ajax',
            reader: {
                type: 'array'
            }
        }
    }
});