/*
 * File: app/view/AdminServicesView.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MEC_App.view.AdminServicesView', {
    extend: 'Ext.Panel',
    alias: 'widget.AdminServicesView',

    requires: [
        'Ext.Label',
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        cls: 'complaint-view',
        itemId: 'AdminServicesView',
        layout: 'fit',
        scrollable: false,
        items: [
            {
                xtype: 'label',
                cls: 'inners-title',
                docked: 'top',
                html: 'الخدمات الإدارية',
                itemId: 'lblTitle'
            },
            {
                xtype: 'list',
                cls: 'HList',
                height: '100%',
                itemId: 'lstViewLinks',
                itemCls: 'HListItem',
                itemTpl: [
                    '<div>{Name}</div>'
                ]
            }
        ],
        listeners: [
            {
                fn: 'onLstLinksItemTap',
                event: 'itemtap',
                delegate: '#lstViewLinks'
            }
        ]
    },

    onLstLinksItemTap: function(dataview, index, target, record, e, eOpts) {

                    Ext.Global.RedirectToView(record.data);



    },

    initialize: function() {
        Ext.Localization.LocalizeView(this);

        var links = Ext.Localization.getLinks(this);



        var store = new Ext.data.Store({
                            data : links
                        });

                var lst = this.down('#lstViewLinks');
                lst.setStore(store);





        this.callParent();
    }

});