/*
 * File: app/view/BarCodeSearchView.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MEC_App.view.BarCodeSearchView', {
    extend: 'Ext.form.Panel',
    alias: 'widget.BarCodeSearchView',

    requires: [
        'Ext.Label',
        'Ext.form.FieldSet',
        'Ext.Button'
    ],

    config: {
        cls: 'complaint-view',
        itemId: 'BarCodeSearchView',
        layout: 'fit',
        scrollable: false,
        items: [
            {
                xtype: 'label',
                cls: 'inners-title',
                docked: 'top',
                html: 'البحث عن معلومات المستخرجات',
                itemId: 'lblTitle'
            },
            {
                xtype: 'fieldset',
                docked: 'top',
                itemId: 'fsForm',
                items: [
                    {
                        xtype: 'label',
                        html: 'إرشادات عن الوثائق التي يمكن استعادة بياناتها ....... '
                    },
                    {
                        xtype: 'button',
                        cls: 'btn-send',
                        itemId: 'btnSearch',
                        text: 'بحث بالماسح الضوئي'
                    }
                ]
            }
        ]
    }

});