/*
 * File: app/view/BusinessIndicatorsView.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MEC_App.view.BusinessIndicatorsView', {
    extend: 'Ext.Panel',
    alias: 'widget.BusinessIndicatorsView',

    requires: [
        'Ext.Label',
        'Ext.Panel',
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        itemId: 'BusinessIndicatorsView',
        layout: 'vbox',
        cls: [
            'complaint-view',
            'rtl'
        ],
        items: [
            {
                xtype: 'label',
                cls: 'inners-title',
                docked: 'top',
                html: 'مؤشرات اقتصادية',
                itemId: 'lblViewTitle'
            },
            {
                xtype: 'panel',
                cls: 'grid-header',
                itemId: 'GridHeader',
                items: [
                    {
                        xtype: 'label'
                    },
                    {
                        xtype: 'label'
                    }
                ]
            },
            {
                xtype: 'panel',
                cls: 'grid-subheader',
                itemId: 'GridSubHeader',
                items: [
                    {
                        xtype: 'label'
                    }
                ]
            },
            {
                xtype: 'list',
                itemId: 'grdMainCRs',
                itemCls: 'grid-table',
                itemTpl: [
                    '<div>List Item {string}</div>'
                ]
            },
            {
                xtype: 'panel',
                cls: 'grid-subheader',
                itemId: 'GridSubHeader1',
                items: [
                    {
                        xtype: 'label'
                    }
                ]
            },
            {
                xtype: 'list',
                itemId: 'grdSubCRs',
                itemCls: 'grid-table',
                itemTpl: [
                    '<div>List Item {string}</div>'
                ]
            },
            {
                xtype: 'panel',
                cls: 'grid-header',
                itemId: 'GridHeader1',
                items: [
                    {
                        xtype: 'label'
                    },
                    {
                        xtype: 'label'
                    }
                ]
            },
            {
                xtype: 'panel',
                cls: 'grid-subheader',
                itemId: 'GridSubHeader2',
                items: [
                    {
                        xtype: 'label'
                    }
                ]
            },
            {
                xtype: 'list',
                itemId: 'grdMainCRs2',
                itemCls: 'grid-table',
                itemTpl: [
                    '<div>List Item {string}</div>'
                ]
            },
            {
                xtype: 'panel',
                cls: 'grid-subheader',
                itemId: 'GridSubHeader3',
                items: [
                    {
                        xtype: 'label'
                    }
                ]
            },
            {
                xtype: 'list',
                itemId: 'grdSubCRs2',
                itemCls: 'grid-table',
                itemTpl: [
                    '<div>List Item {string}</div>'
                ]
            }
        ]
    }

});