/*
 * File: app/view/BusinessIndicatorsView.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MEC_App.view.BusinessIndicatorsView', {
    extend: 'Ext.Panel',
    alias: 'widget.BusinessIndicatorsView',

    requires: [
        'Ext.Label',
        'Ext.Panel',
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        itemId: 'BusinessIndicatorsView',
        layout: 'vbox',
        cls: [
            'complaint-view',
            'rtl'
        ],
        scrollable: {
            direction: 'vertical',
            directionlock: true
        },
        items: [
            {
                xtype: 'label',
                cls: 'inners-title',
                docked: 'top',
                html: 'مؤشرات الأعمال',
                itemId: 'lblViewTitle'
            },
            {
                xtype: 'panel',
                cls: 'grid-header',
                itemId: 'GridHeader',
                items: [
                    {
                        xtype: 'label',
                        html: 'السجلات التجارية الجديدة'
                    },
                    {
                        xtype: 'label'
                    }
                ]
            },
            {
                xtype: 'panel',
                cls: 'grid-subheader',
                itemId: 'GridSubHeader',
                items: [
                    {
                        xtype: 'label',
                        html: 'السجلات الرئيسية'
                    }
                ]
            },
            {
                xtype: 'list',
                itemId: 'grdMainCRs',
                itemCls: 'grid-table',
                itemTpl: [
                    '<div>{MainNewBusinessRegisters.Value}</div>',
                    '<div>{MainNewBusinessRegisters.Change}</div>',
                    ''
                ]
            },
            {
                xtype: 'panel',
                cls: 'grid-subheader',
                itemId: 'GridSubHeader1',
                items: [
                    {
                        xtype: 'label',
                        html: 'السجلات الفرعية'
                    }
                ]
            },
            {
                xtype: 'list',
                itemId: 'grdSubCRs',
                itemCls: 'grid-table',
                itemTpl: [
                    '<div>{MainRenewedBusinessRegisters.Value}</div>',
                    '<div>{MainRenewedBusinessRegisters.Change}</div>',
                    ''
                ]
            },
            {
                xtype: 'panel',
                cls: 'grid-header',
                itemId: 'GridHeader1',
                items: [
                    {
                        xtype: 'label',
                        html: 'السجلات التجارية المجددة'
                    },
                    {
                        xtype: 'label'
                    }
                ]
            },
            {
                xtype: 'panel',
                cls: 'grid-subheader',
                itemId: 'GridSubHeader2',
                items: [
                    {
                        xtype: 'label',
                        html: 'السجلات الرئيسية'
                    }
                ]
            },
            {
                xtype: 'list',
                itemId: 'grdMainCRs2',
                itemCls: 'grid-table',
                itemTpl: [
                    '<div>{MainRenewedBusinessRegisters.Value}</div>',
                    '<div>{MainRenewedBusinessRegisters.Change}</div>',
                    ''
                ]
            },
            {
                xtype: 'panel',
                cls: 'grid-subheader',
                itemId: 'GridSubHeader3',
                items: [
                    {
                        xtype: 'label',
                        html: 'السجلات الفرعية'
                    }
                ]
            },
            {
                xtype: 'list',
                itemId: 'grdSubCRs2',
                itemCls: 'grid-table',
                itemTpl: [
                    '<div>{BranchRenewedBusinessRegisters.Value}</div>',
                    '<div>{BranchRenewedBusinessRegisters.Change}</div>',
                    ''
                ]
            }
        ]
    }

});