/*
 * File: app/view/ContactUs2View.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MEC_App.view.ContactUs2View', {
    extend: 'Ext.Panel',
    alias: 'widget.ContactUs2View',

    requires: [
        'Ext.Panel',
        'Ext.Map',
        'Ext.Spacer',
        'Ext.Button'
    ],

    config: {
        cls: 'contact-us-view',
        layout: 'vbox',
        scrollable: {
            direction: 'vertical',
            directionLock: true
        },
        items: [
            {
                xtype: 'panel',
                html: '<h2 class="contact-us">تواصل معنا</h2>'
            },
            {
                xtype: 'panel',
                html: '<ul><li><a class="call" href="tel:+97444494500">+97444494500</a></li><li><a class="call" href="tel:8005000">8005000</a></li><li><a class="mail" href="mailto:cpd@mec.gov.qa">cpd@mec.gov.qa</a></li></ul>'
            },
            {
                xtype: 'panel',
                html: '<h2 class="branches">الفروع</h2>'
            },
            {
                xtype: 'panel',
                cls: 'map-panel',
                height: 300,
                id: 'map',
                itemId: 'map',
                items: [
                    {
                        xtype: 'map',
                        centered: false,
                        height: 250,
                        itemId: 'mymap',
                        width: '100%',
                        listeners: [
                            {
                                fn: function(component, eOpts) {
                                    var gMap = this.getMap();


                                    //gMap.setCenter(new google.maps.LatLng (25.321283,51.528329));




                                },
                                event: 'initialize'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'panel',
                layout: 'hbox',
                items: [
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        itemId: 'youtube',
                        icon: 'true',
                        iconAlign: 'center',
                        iconCls: 'youtube'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        itemId: 'instagram',
                        icon: 'true',
                        iconAlign: 'center',
                        iconCls: 'instagram'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        itemId: 'twitter',
                        icon: 'true',
                        iconAlign: 'center',
                        iconCls: 'twitter'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        itemId: 'facebook',
                        icon: 'true',
                        iconAlign: 'center',
                        iconCls: 'youtube'
                    },
                    {
                        xtype: 'spacer'
                    }
                ]
            }
        ]
    },

    initialize: function() {
        this.callParent();



        Ext.Function.defer(function(){

            var mapPanel = this.down('map');
          var gMap = mapPanel.getMap();

          if (gMap === null) {
           Ext.Function.defer(this.initMap,250,this);
          } else {
             // ready to start calling google map methods

             // alert('not null');


          gMap.setCenter(new google.maps.LatLng (25.321283,51.528329));


              var marker = new google.maps.Marker({
            map: gMap,
            animation: google.maps.Animation.DROP,
            position: new google.maps.LatLng (25.321283,51.528329),
            icon: 'resources/images/drop-pin.png'
           });





          }
        } ,100,this);


    }

});