/*
 * File: app/view/DailyReportView.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MEC_App.view.DailyReportView', {
    extend: 'Ext.Panel',
    alias: 'widget.DailyReportView',

    requires: [
        'Ext.Label',
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        cls: 'complaint-view',
        itemId: 'DailyReportView',
        layout: 'fit',
        scrollable: false,
        items: [
            {
                xtype: 'label',
                cls: 'inners-title',
                docked: 'top',
                html: 'النشرة اليومية'
            },
            {
                xtype: 'list',
                cls: 'CompanyList',
                height: '100%',
                itemId: 'lstItems',
                itemTpl: [
                    '<div class=\'CompanyListItem\'>{Name}</div>'
                ]
            }
        ],
        listeners: [
            {
                fn: 'onLstItemsItemTap',
                event: 'itemtap',
                delegate: '#lstItems'
            }
        ]
    },

    onLstItemsItemTap: function(dataview, index, target, record, e, eOpts) {


        if (record.data.Url.indexOf('http')>0){
                window.open(record.data.Url,'_blank');
        }else{
                Ext.Viewport.getActiveItem().push({
                    xtype: record.data.Url,
                    title: Ext.Global.GetFixedTitle()
                });
            }


    },

    initialize: function() {
        this.callParent();


        var links = [{Name:'الاسعار اليومية',Url:'DailyPricesView'},
                     {Name:'أسعار السلع الاستهلاكية',Url:'GoodsPricesView'}
                    ];

        var store = new Ext.data.Store({
                            data : links
                        });

                var lst = this.down('#lstItems');
                lst.setStore(store);












    }

});