/*
 * File: app/view/GoodPriceListView.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MEC_App.view.GoodPriceListView', {
    extend: 'Ext.Panel',
    alias: 'widget.GoodPriceListView',

    requires: [
        'Ext.Label',
        'Ext.Panel',
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        itemId: 'GoodPriceListView',
        layout: 'vbox',
        scrollable: false,
        cls: [
            'complaint-view',
            'rtl'
        ],
        items: [
            {
                xtype: 'label',
                cls: 'inners-title',
                docked: 'top',
                html: 'Test',
                itemId: 'lblTitle'
            },
            {
                xtype: 'panel',
                cls: 'grid-header',
                docked: 'top',
                layout: 'hbox',
                items: [
                    {
                        xtype: 'label',
                        flex: 3,
                        cls: 'header-cell1',
                        html: 'اسم المحل',
                        itemId: 'shopName'
                    },
                    {
                        xtype: 'label',
                        flex: 2,
                        cls: 'header-cell2',
                        html: 'السعر',
                        itemId: 'lblPrice'
                    }
                ]
            },
            {
                xtype: 'list',
                itemId: 'lstPrices',
                itemCls: 'grid-row',
                itemTpl: [
                    '',
                    '<div class="x-horizontal x-align-stretch x-pack-start x-layout-box">',
                    '    <div class=\'row-cell-fix x-layout-box-item x-flexed x-stretched\' style=\'-webkit-box-flex:3\'>{Shop.ShopName}</div>    ',
                    '    <div class=\'row-cell-fix x-layout-box-item x-flexed x-stretched\' style=\'-webkit-box-flex:2\'>{Price}</div>     ',
                    '</div>',
                    ''
                ],
                striped: true
            }
        ]
    }

});