/*
 * File: app/view/GoodPriceListView.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MEC_App.view.GoodPriceListView', {
    extend: 'Ext.Panel',
    alias: 'widget.GoodPriceListView',

    requires: [
        'Ext.Label',
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        cls: 'complaint-view',
        itemId: 'GoodPriceListView',
        layout: 'fit',
        scrollable: false,
        items: [
            {
                xtype: 'label',
                cls: 'inners-title',
                docked: 'top',
                html: 'Test',
                itemId: 'lblTitle'
            },
            {
                xtype: 'list',
                cls: 'CompanyList',
                height: '100%',
                itemId: 'lstPrices',
                itemCls: 'item-product',
                itemTpl: [
                    '<div class=\'tabl-row\'>',
                    '    <div class=\'tabl-cell\'>{Shop.ShopName}</div>    ',
                    '    <div class=\'tabl-cell\'>{Price}</div>    ',
                    '</div>'
                ],
                items: [
                    {
                        xtype: 'label',
                        cls: 'table-header',
                        docked: 'top',
                        html: 'اسم المحل'
                    },
                    {
                        xtype: 'label',
                        cls: 'table-header',
                        docked: 'top',
                        html: 'السعر'
                    }
                ]
            }
        ]
    }

});