/*
 * File: app/view/InvestorEducationView.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MEC_App.view.InvestorEducationView', {
    extend: 'Ext.Panel',
    alias: 'widget.InvestorEducationView',

    requires: [
        'Ext.Label',
        'Ext.dataview.List',
        'Ext.XTemplate',
        'Ext.plugin.ListPaging'
    ],

    config: {
        cls: 'complaint-view',
        itemId: 'InvestorEducationView',
        layout: 'fit',
        scrollable: false,
        items: [
            {
                xtype: 'label',
                cls: 'inners-title',
                docked: 'top',
                html: 'ثقافة المستثمر',
                itemId: 'lblTitle'
            },
            {
                xtype: 'list',
                cls: 'CompanyList',
                height: '100%',
                itemId: 'lstEducation',
                itemCls: 'item-education',
                itemTpl: Ext.create('Ext.XTemplate', 
                    '{ArticleTitle}',
                    '<br />',
                    '<img class="img" src="{[this.getImgSrc(values.Id)]}" />',
                    '',
                    {
                        getImgSrc: function(Id) {
                            var src = Ext.Global.GetConfig('CMSWSUrl')+"/InvestorEducation/Image/"+Id;
                            return src;
                        }
                    }
                ),
                scrollToTopOnRefresh: false,
                plugins: [
                    {
                        autoPaging: true,
                        type: 'listpaging'
                    }
                ]
            }
        ]
    }

});