/*
 * File: app/view/MediaCenterView.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MEC_App.view.MediaCenterView', {
    extend: 'Ext.Panel',
    alias: 'widget.MediaCenterView',

    requires: [
        'Ext.Panel',
        'Ext.Label',
        'Ext.Button',
        'Ext.Spacer'
    ],

    config: {
        fullscreen: true,
        itemId: 'publicserviceview1',
        layout: 'fit',
        items: [
            {
                xtype: 'panel',
                layout: 'vbox',
                items: [
                    {
                        xtype: 'panel',
                        flex: 1,
                        cls: 'services-header',
                        height: '30%',
                        layout: 'vbox',
                        items: [
                            {
                                xtype: 'panel',
                                cls: 'services-header-overlay',
                                height: '100%',
                                layout: 'vbox',
                                items: [
                                    {
                                        xtype: 'panel',
                                        flex: 2,
                                        cls: 'service-header-icon'
                                    },
                                    {
                                        xtype: 'label',
                                        flex: 1,
                                        cls: 'service-header-title',
                                        html: 'المركز الاعلامي'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        flex: 2.2,
                        cls: 'inner-panel',
                        height: 'auto',
                        scrollable: 'vertical',
                        items: [
                            {
                                xtype: 'panel',
                                layout: 'vbox',
                                items: [
                                    {
                                        xtype: 'panel',
                                        cls: 'services-list-panel',
                                        layout: 'hbox',
                                        items: [
                                            {
                                                xtype: 'button',
                                                flex: 1,
                                                itemId: 'btnPublications',
                                                iconAlign: 'top',
                                                iconCls: 'icon-my-business',
                                                text: 'اصدارات الوزارة'
                                            },
                                            {
                                                xtype: 'button',
                                                flex: 1,
                                                itemId: 'btnMinistryNews',
                                                iconAlign: 'top',
                                                iconCls: 'icon-print-office',
                                                text: 'اصداء عن الوزارة'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'panel',
                                        cls: 'services-list-panel',
                                        layout: 'hbox',
                                        items: [
                                            {
                                                xtype: 'button',
                                                flex: 1,
                                                itemId: 'btnNews',
                                                iconAlign: 'top',
                                                iconCls: 'icon-my-request',
                                                text: 'اخبار اقتصادية'
                                            },
                                            {
                                                xtype: 'spacer',
                                                flex: 1
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ]
    },

    initialize: function() {
        this.callParent();

        this.down('#btnPublications').setHtml(Ext.Global.GetViewTitle('MinistryPublications'));
        this.down('#btnMinistryNews').setHtml(Ext.Global.GetViewTitle('MinistryNews'));
        this.down('#btnNews').setHtml(Ext.Global.GetViewTitle('EconomyNews'));







    }

});