/*
 * File: app/view/MinistryNewsSection4View.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MEC_App.view.MinistryNewsSection4View', {
    extend: 'Ext.dataview.List',
    alias: 'widget.MinistryNewsSection4View',

    requires: [
        'Ext.Label',
        'Ext.XTemplate',
        'Ext.plugin.PullRefresh',
        'Ext.plugin.ListPaging'
    ],

    config: {
        cls: 'news-lstng',
        fullscreen: true,
        height: '100%',
        itemId: 'NewsList',
        defaultType: 'NewsListItem',
        store: 'MinistryNewsStore',
        infinite: true,
        itemHeight: 80,
        onItemDisclosure: true,
        pinHeaders: false,
        useSimpleItems: false,
        variableHeights: true,
        itemTpl: [
            '<div>{text}</div>'
        ],
        items: [
            {
                xtype: 'label',
                cls: 'inners-title',
                docked: 'top',
                html: 'اخبار اقتصادية اقليمية'
            }
        ],
        plugins: [
            {
                type: 'pullrefresh'
            },
            {
                autoPaging: true,
                type: 'listpaging'
            }
        ]
    }

});