/*
 * File: app/view/MyEstablishmentDetails.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MEC_App.view.MyEstablishmentDetails', {
    extend: 'Ext.Panel',

    requires: [
        'Ext.Panel',
        'Ext.TitleBar',
        'Ext.Label',
        'Ext.dataview.List',
        'Ext.XTemplate',
        'MEC_App.controller.AnimationHelper'
    ],

    config: {
        fullscreen: true,
        itemId: 'MyEstablishmentDetails',
        layout: 'vbox',
        scrollable: {
            direction: 'vertical',
            directionLock: true
        },
        items: [
            {
                xtype: 'panel',
                cls: 'acc-container',
                itemId: 'EstablishmentInfo',
                items: [
                    {
                        xtype: 'titlebar',
                        cls: 'acc-header',
                        docked: 'top',
                        itemId: 'mytitlebar',
                        title: 'بيانات المنشاة',
                        titleAlign: 'right',
                        listeners: [
                            {
                                fn: function(element, eOpts) {
                                    Ext.AnimationHelper.HandleShowHidePanel(element,'pnlData');

                                },
                                event: 'painted'
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        cls: 'acc-group',
                        id: 'pnlData1',
                        itemId: 'pnlData',
                        items: [
                            {
                                xtype: 'label',
                                html: ' رقم السجل التجاري',
                                id: 'commercialRegistration2'
                            },
                            {
                                xtype: 'label',
                                cls: 'label-value',
                                html: ' ',
                                id: 'commercialRegistration3'
                            },
                            {
                                xtype: 'label',
                                html: 'تاريخ التسجيل',
                                id: 'commercialRegistrationIssueDate2'
                            },
                            {
                                xtype: 'label',
                                cls: 'label-value',
                                id: 'commercialRegistrationIssueDate3'
                            },
                            {
                                xtype: 'label',
                                html: 'تاريخ الانتهاء',
                                id: 'commercialRegistrationExpiryDate2'
                            },
                            {
                                xtype: 'label',
                                cls: 'label-value',
                                id: 'commercialRegistrationExpiryDate3'
                            },
                            {
                                xtype: 'label',
                                html: 'حالة السجل التجاري',
                                id: 'commercialRegistrationStatus2'
                            },
                            {
                                xtype: 'label',
                                cls: 'label-value',
                                id: 'commercialRegistrationStatus3'
                            },
                            {
                                xtype: 'label',
                                html: 'اسم السجل التجاري بالإنجليزية',
                                id: 'establishmentEnglishName2'
                            },
                            {
                                xtype: 'label',
                                cls: 'label-value',
                                id: 'establishmentEnglishName3'
                            },
                            {
                                xtype: 'label',
                                html: 'اسم السجل التجاري بالعربية',
                                id: 'establishmentArabicName2'
                            },
                            {
                                xtype: 'label',
                                cls: 'label-value',
                                id: 'establishmentArabicName3'
                            },
                            {
                                xtype: 'label',
                                html: 'راس مال الشركة',
                                id: 'companyCapital2'
                            },
                            {
                                xtype: 'label',
                                cls: 'label-value',
                                id: 'companyCapital3'
                            },
                            {
                                xtype: 'label',
                                html: 'رقم الرخصة التجارية',
                                id: 'commercialPermit2'
                            },
                            {
                                xtype: 'label',
                                cls: 'label-value',
                                id: 'commercialPermit3'
                            },
                            {
                                xtype: 'label',
                                html: 'حالة الرخصة التجارية',
                                id: 'commercialPermitStatus2'
                            },
                            {
                                xtype: 'label',
                                cls: 'label-value',
                                id: 'commercialPermitStatus3'
                            },
                            {
                                xtype: 'label',
                                html: 'تاريخ انتهاء الرخصة التجارية',
                                id: 'commercialPermitExpiryDate2'
                            },
                            {
                                xtype: 'label',
                                cls: 'label-value',
                                id: 'commercialPermitExpiryDate3'
                            },
                            {
                                xtype: 'label',
                                html: 'تاريخ التاسيس',
                                id: 'establishmentDate2'
                            },
                            {
                                xtype: 'label',
                                cls: 'label-value',
                                id: 'establishmentDate3'
                            },
                            {
                                xtype: 'label',
                                html: 'نوع المنشاة',
                                id: 'establishmentType2'
                            },
                            {
                                xtype: 'label',
                                cls: 'label-value',
                                id: 'establishmentType3'
                            },
                            {
                                xtype: 'label',
                                html: 'الشكل القانوني',
                                id: 'establishmentLegalForm2'
                            },
                            {
                                xtype: 'label',
                                cls: 'label-value',
                                id: 'establishmentLegalForm3'
                            },
                            {
                                xtype: 'label',
                                html: 'حالة المنشاة',
                                id: 'establishmentStatus2'
                            },
                            {
                                xtype: 'label',
                                cls: 'label-value',
                                id: 'establishmentStatus3'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'panel',
                cls: 'acc-container',
                hidden: false,
                itemId: 'BusinessActivities',
                items: [
                    {
                        xtype: 'titlebar',
                        cls: 'acc-header',
                        docked: 'top',
                        itemId: 'mytitlebar',
                        title: 'الانشطة التجارية',
                        titleAlign: 'right',
                        listeners: [
                            {
                                fn: function(element, eOpts) {
                                    Ext.AnimationHelper.HandleShowHidePanel(element,'pnlData2');

                                },
                                event: 'painted'
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        cls: 'acc-group',
                        id: 'pnlData4',
                        itemId: 'pnlData2',
                        items: [
                            {
                                xtype: 'list',
                                id: 'lstBizActivities1',
                                itemTpl: [
                                    '<div>List Item {string}</div>'
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'panel',
                cls: 'acc-container',
                hidden: false,
                itemId: 'Branches',
                items: [
                    {
                        xtype: 'titlebar',
                        cls: 'acc-header',
                        docked: 'top',
                        itemId: 'mytitlebar',
                        title: 'الفروع',
                        titleAlign: 'right',
                        listeners: [
                            {
                                fn: function(element, eOpts) {
                                    Ext.AnimationHelper.HandleShowHidePanel(element,'pnlData3');

                                },
                                event: 'painted'
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        cls: 'acc-group',
                        id: 'pnlData5',
                        itemId: 'pnlData3',
                        items: [
                            {
                                xtype: 'list',
                                id: 'lstBranches1',
                                itemCls: 'item-branch',
                                itemTpl: [
                                    '<div class=\'tpl-branch-1\'>{branchName}</div>',
                                    '',
                                    '<div class=\'tpl-branch-2\'>{status}</div>',
                                    '',
                                    ''
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'panel',
                cls: 'acc-container',
                itemId: 'Signatories',
                items: [
                    {
                        xtype: 'titlebar',
                        cls: 'acc-header',
                        docked: 'top',
                        itemId: 'mytitlebar',
                        title: 'المخولين بالتوقيع',
                        titleAlign: 'right',
                        listeners: [
                            {
                                fn: function(element, eOpts) {
                                    Ext.AnimationHelper.HandleShowHidePanel(element,'lstSignatories');

                                },
                                event: 'painted'
                            }
                        ]
                    },
                    {
                        xtype: 'list',
                        id: 'lstSignatories1',
                        itemCls: 'item-signatory',
                        itemTpl: [
                            '',
                            '    <div class=\'tpl-signatory-1\'>{fullNameARA}</div>',
                            '    <div class=\'tpl-signatory-2\'><span class=\'FA\'>{type}</span> <span class=\'FB\'>{nationality}</span></div>',
                            '',
                            ''
                        ],
                        scrollToTopOnRefresh: false
                    }
                ]
            }
        ]
    }

});