/*
 * File: app/view/NewsDetailsView.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MEC_App.view.NewsDetailsView', {
    extend: 'Ext.Panel',
    alias: 'widget.NewsDetailsView',

    requires: [
        'Ext.Panel',
        'Ext.Label',
        'Ext.Img'
    ],

    config: {
        id: 'NewsDetailsView',
        itemId: 'NewsDetailsView',
        layout: 'vbox',
        items: [
            {
                xtype: 'panel'
            },
            {
                xtype: 'panel',
                flex: 1,
                cls: 'newsDetails',
                items: [
                    {
                        xtype: 'label',
                        cls: 'title',
                        height: 40,
                        html: '',
                        id: 'lblTitle'
                    },
                    {
                        xtype: 'image',
                        cls: 'img',
                        height: 201,
                        id: 'imgNews'
                    },
                    {
                        xtype: 'label',
                        cls: 'date',
                        height: 40,
                        id: 'lblDate'
                    },
                    {
                        xtype: 'label',
                        cls: 'details',
                        id: 'lblDetails'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onNewsDetailsViewInitialize',
                event: 'initialize'
            }
        ]
    },

    onNewsDetailsViewInitialize: function(component, eOpts) {

         this.down('#lblTitle').setHtml(this.Data.NewsTitle);
         this.down('#lblDate').setHtml(this.Data.NewsDate);
         this.down('#lblDetails').setHtml(this.Data.NewsDetails);
         this.down('#imgNews').setSrc(this.Data.NewsImgUrl);


    }

});