/*
 * File: app/view/PrintOffsView1.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MEC_App.view.PrintOffsView1', {
    extend: 'Ext.form.Panel',
    alias: 'widget.PrintOffsView1',

    requires: [
        'Ext.Label',
        'Ext.form.FieldSet',
        'Ext.field.Hidden',
        'Ext.Button',
        'MEC_App.controller.DeviceController'
    ],

    config: {
        cls: 'complaint-view',
        itemId: 'PrintOffsView1',
        layout: 'vbox',
        enableSubmissionForm: false,
        items: [
            {
                xtype: 'label',
                cls: 'inners-title',
                html: 'طلب مستخرجات'
            },
            {
                xtype: 'fieldset',
                flex: 1,
                scrollable: {
                    direction: 'vertical',
                    directionLock: true
                },
                items: [
                    {
                        xtype: 'textfield',
                        itemId: 'companyName',
                        label: 'اسم الشركة',
                        required: true,
                        placeHolder: 'اسم الشركة',
                        readOnly: true,
                        listeners: [
                            {
                                fn: function(component, eOpts) {

                                    // Create Native drop down
                                    var me = this;



                                    me.element.on('tap', function(){


                                        var data = me.up('PrintOffsView1').getData();



                                        var items = [];

                                        Ext.each(data, function(item){
                                            items.push({ text: item.establishmentArabicName, value: item.commercialRegistration });
                                        });




                                        var btn = this;
                                        var config = {
                                            title: "نوع الشكوي",
                                            items: items,
                                            //selectedValue: "2",
                                            doneButtonLabel: "اختيار",
                                            cancelButtonLabel: "الغاء"
                                        };


                                        var hiddenCompanyCR = Ext.ComponentQuery.query("#hiddenCompanyCR")[0];

                                        Ext.DeviceController.ShowNativePickerWithValue(me, hiddenCompanyCR,config);


                                    }, me);


                                },
                                event: 'initialize'
                            }
                        ]
                    },
                    {
                        xtype: 'hiddenfield',
                        itemId: 'hiddenCompanyCR',
                        value: '//39193'
                    },
                    {
                        xtype: 'textfield',
                        itemId: 'txtPrintoutType',
                        label: 'نوع المستخرج',
                        value: 52,
                        placeHolder: 'نوع المستخرج',
                        readOnly: true,
                        listeners: [
                            {
                                fn: function(component, eOpts) {

                                    // Create Native drop down
                                    var me = this;

                                    me.element.on('tap', function(){

                                        var btn = this;
                                        var config = {
                                            title: "نوع المستخرج",
                                            items: [

                                            { text: "مستخرج سجل تجاري - العربية", value: "51" },
                                            { text: "مستخرج سجل تجاري - انجليزي", value: "52" },
                                            { text: "شهادة عن رخصة تجارية", value: "53" },
                                            { text: "شهادة عدم ملكية", value: "50" }

                                            ],
                                            selectedValue: "",
                                            doneButtonLabel: "اختيار",
                                            cancelButtonLabel: "الغاء"
                                        };

                                        var hiddenPrintType = Ext.ComponentQuery.query("#hiddenPrintoutType")[0];

                                        Ext.DeviceController.ShowNativePickerWithValue(me,hiddenPrintType, config);

                                    }, me);







                                },
                                event: 'initialize'
                            }
                        ]
                    },
                    {
                        xtype: 'hiddenfield',
                        itemId: 'hiddenPrintoutType',
                        value: '//50'
                    },
                    {
                        xtype: 'textfield',
                        hidden: false,
                        itemId: 'txtDeliveryMethod',
                        label: 'طريقة الاستلام',
                        placeHolder: 'طريقة الاستلام',
                        readOnly: true,
                        listeners: [
                            {
                                fn: function(component, eOpts) {

                                    // add tab function on text field
                                    var me = this;
                                    me.element.on('tap', function(){

                                        var btn = this;
                                        var config = {
                                            title: "طريقة الاستلام",
                                            items: [
                                            { text: "شخصي", value: "1" },
                                            { text: "البريد", value: "2" },
                                            { text: "البريد الالكتروني", value: "3" }



                                            ],
                                            selectedValue: "",
                                            doneButtonLabel: "اختيار",
                                            cancelButtonLabel: "الغاء"
                                        };


                                        var hiddenDeliveryMethod = Ext.ComponentQuery.query("#hiddenDeliveryMethod")[0];

                                        Ext.DeviceController.ShowNativePickerWithValue(me,hiddenDeliveryMethod, config);


                                    }, me);



                                },
                                event: 'initialize'
                            }
                        ]
                    },
                    {
                        xtype: 'hiddenfield',
                        itemId: 'hiddenDeliveryMethod'
                    },
                    {
                        xtype: 'textfield',
                        itemId: 'txtNoOfCopies',
                        label: 'عدد النسخ',
                        placeHolder: 'عدد النسخ'
                    },
                    {
                        xtype: 'button',
                        cls: 'btn-send',
                        itemId: 'btnPrintoffsNext',
                        text: 'التالي'
                    }
                ]
            }
        ]
    },

    initialize: function() {
        this.callParent();

        /*
        this.down('#shopName').setPlaceHolder(Ext.Global.GetComplaintsTitle('shopName'))
        .setLabel(Ext.Global.GetComplaintsTitle('shopName'));


        this.down('#shopLocation').setPlaceHolder(Ext.Global.GetComplaintsTitle('shopLocation'))
        .setLabel(Ext.Global.GetComplaintsTitle('shopLocation'));

        this.down('#txtCategory').setPlaceHolder(Ext.Global.GetComplaintsTitle('ComplaintType'))
        .setLabel(Ext.Global.GetComplaintsTitle('ComplaintType'));

        this.down('#txtComplaint').setPlaceHolder(Ext.Global.GetComplaintsTitle('txtComplaint'))
        .setLabel(Ext.Global.GetComplaintsTitle('txtComplaint'));

        this.down('#fullName').setPlaceHolder(Ext.Global.GetComplaintsTitle('fullName'))
        .setLabel(Ext.Global.GetComplaintsTitle('fullName'));

        this.down('#email').setPlaceHolder(Ext.Global.GetComplaintsTitle('email'))
        .setLabel(Ext.Global.GetComplaintsTitle('email'));

        this.down('#mobile').setPlaceHolder(Ext.Global.GetComplaintsTitle('mobile'))
        .setLabel(Ext.Global.GetComplaintsTitle('mobile'));


        this.down('#txtBarCode').setPlaceHolder(Ext.Global.GetComplaintsTitle('barcode'))
        .setLabel(Ext.Global.GetComplaintsTitle('barcode'));


        this.down('#lblAttachImage').setHtml(Ext.Global.GetComplaintsTitle('AttachImg'));

        this.down('#btnSubmitComplaint').setText(Ext.Global.GetComplaintsTitle('Submit'));

        */


        //this.setData('test');


    }

});