/*
 * File: app/view/ProjectsView.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MEC_App.view.ProjectsView', {
    extend: 'Ext.Panel',
    alias: 'widget.ProjectsView',

    requires: [
        'Ext.Label',
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        cls: 'complaint-view',
        itemId: 'ProjectsView',
        layout: 'fit',
        scrollable: false,
        items: [
            {
                xtype: 'label',
                cls: 'inners-title',
                docked: 'top',
                html: 'المبادرات والمشاريع',
                itemId: 'lblTitle'
            },
            {
                xtype: 'list',
                cls: 'CompanyList',
                height: '100%',
                itemId: 'lstProjects',
                itemCls: 'item-recall',
                itemTpl: Ext.create('Ext.XTemplate', 
                    '<div class=\'tpl-recall-1 FA\'><img src="{[this.getImgSrc(values.Id)]}" /></div>',
                    '<div class=\'tpl-recall-2 FA\'><span>{ProjectTitle}</span></div>',
                    '',
                    {
                        getImgSrc: function(Id) {

                            var src = Ext.Global.GetConfig('CMSWSUrl')+"/InitiativesAndProject/Image/"+Id;
                            return src;

                        }
                    }
                )
            }
        ]
    },

    initialize: function() {

        this.callParent();

        Ext.Localization.LoadLocalization();

        Ext.Localization.LocalizeView(this);

    }

});