/*
 * File: app/view/ProjectsView.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MEC_App.view.ProjectsView', {
    extend: 'Ext.Panel',
    alias: 'widget.ProjectsView',

    requires: [
        'Ext.Panel',
        'Ext.Label',
        'Ext.dataview.List',
        'Ext.XTemplate',
        'Ext.plugin.ListPaging'
    ],

    config: {
        cls: 'complaint-view',
        fullscreen: true,
        itemId: 'ProjectsView',
        layout: 'vbox',
        items: [
            {
                xtype: 'panel',
                flex: 1,
                cls: 'services-header',
                layout: 'vbox',
                items: [
                    {
                        xtype: 'panel',
                        cls: 'services-header-overlay',
                        height: '100%',
                        layout: 'vbox',
                        items: [
                            {
                                xtype: 'panel',
                                flex: 2,
                                cls: 'projects-header-icon'
                            },
                            {
                                xtype: 'label',
                                flex: 1,
                                cls: 'service-header-title',
                                html: 'المبادرات والمشاريع',
                                itemId: 'lblTitle'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'list',
                flex: 2.7,
                cls: 'news-lstng',
                height: 'auto',
                itemId: 'lstProjects',
                itemTpl: Ext.create('Ext.XTemplate', 
                    '<div class="x-horizontal x-align-stretch x-pack-start x-layout-box">',
                    '    <div class="x-img x-img-image lstng-img x-img-background x-layout-box-item x-flexed x-stretched" style="-webkit-box-flex: 2; background-image: url({[this.getImgSrc(values.Id)]});"></div>',
                    '    <div class="lstng-title x-layout-box-item x-flexed x-stretched" style="-webkit-box-flex: 7;"><span>{ProjectTitle}</span></div>',
                    '</div>',
                    {
                        getImgSrc: function(Id) {
                            var img = new Image();
                            var src = Ext.Global.GetConfig('CMSWSUrl')+"/InitiativesAndProject/Image/"+Id;

                            return src;
                        }
                    }
                ),
                scrollToTopOnRefresh: false,
                onItemDisclosure: true,
                pinHeaders: false,
                useSimpleItems: false,
                plugins: [
                    {
                        autoPaging: true,
                        type: 'listpaging'
                    }
                ]
            }
        ]
    },

    initialize: function() {

        this.callParent();

        Ext.Localization.LoadLocalization();

        Ext.Localization.LocalizeView(this);

    }

});