/*
 * File: app/view/SupplyServiceView1.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MEC_App.view.SupplyServiceView1', {
    extend: 'Ext.form.Panel',
    alias: 'widget.SupplyServiceView1',

    requires: [
        'Ext.Label',
        'Ext.Panel',
        'Ext.TitleBar',
        'Ext.form.FieldSet',
        'Ext.Button',
        'Ext.field.Spinner'
    ],

    config: {
        itemId: 'SupplyServiceView1',
        scrollable: 'vertical',
        cls: [
            'complaint-view',
            'rtl'
        ],
        items: [
            {
                xtype: 'label',
                cls: 'inners-title',
                html: 'نموذج طلب تموين',
                itemId: 'viewLbl'
            },
            {
                xtype: 'panel',
                cls: 'acc-container',
                height: 300,
                itemId: 'frmSupplyService1',
                items: [
                    {
                        xtype: 'titlebar',
                        cls: 'acc-header3',
                        docked: 'top',
                        itemId: 'itemQuantityTitle',
                        title: 'الاصناف والكميات',
                        titleAlign: 'right'
                    },
                    {
                        xtype: 'fieldset',
                        itemId: 'fsItems'
                    }
                ]
            },
            {
                xtype: 'button',
                cls: 'btn-send',
                itemId: 'btnSupplyNext1',
                text: 'التالي'
            },
            {
                xtype: 'label',
                html: 'الكميات بالاعلي هي الكميات المتاحة في رصيد المستخدم',
                itemId: 'lblAllowedQuantities'
            }
        ]
    }

});