/*
 * File: app/view/SupplyServiceHowTo.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MEC_App.view.SupplyServiceHowTo', {
    extend: 'Ext.Panel',
    alias: 'widget.SupplyServiceHowTo',

    requires: [
        'Ext.Label',
        'Ext.Panel'
    ],

    config: {
        fullscreen: true,
        itemId: 'SupplyServiceHowTo',
        layout: 'vbox',
        cls: [
            'complaint-view',
            'rtl'
        ],
        items: [
            {
                xtype: 'label',
                cls: 'inners-title',
                docked: 'top',
                html: 'كيفية الحصول على خدمات التموين',
                id: 'lblTitle',
                itemId: 'lblTitle'
            },
            {
                xtype: 'panel',
                flex: 1,
                cls: [
                    'text-panel',
                    'supply-text'
                ],
                height: 'auto',
                scrollable: {
                    direction: 'vertical',
                    directionLock: true
                },
                items: [
                    {
                        xtype: 'label',
                        html: 'ان كنت حاصلاً على بطاقة الحصص التموينية، يمكن الدخول على خدمة طلب شراء المواد التموينية وذلك بأدخال رقم بطاقتك الشخصيه  وكلمة المرور الخاصه بك بعد انشاء حسابك من خلال البرنامج، وسيتم إرسال رسالة نصية لتفعيل الحساب الخاص بك.<br/> <br /> في حال عدم حيازتك لبطاقة السلع التموينية وتطابق الشروط التالي بيانها على أفراد اسرتك، يرجى التكرم بملئ النموذج على <a id="lnk1" href="#"> الرابط التالي </a>   وإرساله على البريد الالكتروني: <a href="mailto:tamween@mec.gov.qa">tamween@mec.gov.qa</a><br/><br/>لأي استفسارات يرجى التكرم بالتواصل مع ادارة التموين عبر المعلومات التالية:<br/>هاتف رقم: <a href="tel:44378160">٤٤٣٧٨١٦٠</a> / <a href="tel:44378162">٤٤٣٧٨١٦٢</a><br/>بريد إلكتروني: <a href="mailto:tamween@mec.gov.qa">tamween@mec.gov.qa</a><br/>او عبر مقر الادارة الكائن في منطقة المنتزه، شارع الروابي',
                        itemId: 'GeneralInfo'
                    },
                    {
                        xtype: 'label',
                        cls: 'inner-title',
                        html: 'المستندات التأهيلية للحصول على بطاقة الحصص التموينية',
                        itemId: 'SuppliesCardTitle2'
                    },
                    {
                        xtype: 'label',
                        cls: 'text-container',
                        html: '<ol><li>صورة من البطاقة الشخصية للزوج والزوجة وأفراد الاسرة</li><li>عقد الزواج ان لم يكن هناك أبناء</li></ol><br/> *في حالة عدم توفر البطاقة الشخصية للابناء فيمكن التسجيل باستخدام شهادة الميلاد موضحاً بها الأرقام الشخصية.',
                        itemId: 'SuppliesCardDesc2'
                    },
                    {
                        xtype: 'label',
                        cls: 'inner-title',
                        html: 'هناك متطلبات خاصة بالحالات التالية',
                        itemId: 'SuppliesCardTitle'
                    },
                    {
                        xtype: 'label',
                        cls: 'text-container',
                        html: '<ol><li>في حالة وفاة رب الاسرة :<ul><li>صورة من شهادة الوفاة</li><li>صورة من البطاقة الشخصية او شهادة الميلاد للأبناء</li></ul></li><li>في حالة الطلاق<ul><li>صورة من شهادة الطلاق</li><li>صورة من البطاقة الشخصية</li><li>صورة من شهادة الميلاد للأبناء</li><li>صورة من حضانة على الابناء</li></ul></li></ol>',
                        itemId: 'SuppliesCardDesc'
                    },
                    {
                        xtype: 'label',
                        cls: 'inner-title',
                        html: 'المستندات التأهيلية للحصول على بطاقة تموين الأعلاف',
                        itemId: 'FodderCardTitle'
                    },
                    {
                        xtype: 'label',
                        cls: 'text-container',
                        html: '<ol><li>صورة من البطاقة الشخصية</li><li>شهادة حيازة مواشي صادرة من وزارة البيئة - ادارة الثروة الحيوانية</li></ol>',
                        itemId: 'FodderCardDesc'
                    },
                    {
                        xtype: 'label',
                        cls: 'inner-title',
                        html: 'الحصص التموينية الشهرية',
                        itemId: 'SuppliesCardTitle1'
                    },
                    {
                        xtype: 'label',
                        cls: 'text-container',
                        html: '<ol><li>الرز والسكر<ul><li>يصرف عدد ١ كيس رز اضافة الى عدد ١ كيس سكر لكل ٣ أفراد من الاسرة شهرياً</li></ul></li><li>الزيت والحليب<ul><li>يصرف عدد ١ كرتون زيت وعدد ١ كرتون حليب لكل ٤ أفراد من الاسرة شهرياً</li></ul></li></ol>',
                        itemId: 'SuppliesCardDesc1'
                    }
                ]
            }
        ]
    },

    initialize: function() {
        this.callParent();

        Ext.Localization.LoadLocalization();

        Ext.Localization.LocalizeView(this);

        Ext.defer(function(){
            document.getElementById('lnk1').addEventListener("click",
                                                             function(){

                                                                 //alert(2);
        if(Ext.Global.LanguageFlag=='ar')
        {
            window.open("http://www.mec.gov.qa/Arabic/Services/Pages/AllServices.aspx","_system");
        }else{
        window.open("http://www.mec.gov.qa/English/Services/Pages/AllServices.aspx","_system");
        }





                                                             });


        },400);
    }

});