/*
 * File: app/view/TradeExchangeView.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MEC_App.view.TradeExchangeView', {
    extend: 'Ext.Panel',
    alias: 'widget.TradeExchangeView',

    requires: [
        'Ext.Label',
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        cls: 'complaint-view',
        itemId: 'TradeExchangeView',
        layout: 'fit',
        scrollable: false,
        items: [
            {
                xtype: 'label',
                cls: 'inners-title',
                docked: 'top',
                html: 'تقارير التبادل التجاري',
                itemId: 'lblTitle'
            },
            {
                xtype: 'list',
                cls: 'HList',
                height: '100%',
                itemId: 'lstViewLinks',
                itemCls: 'HListItem',
                itemTpl: [
                    '<div>{Title}</div>'
                ]
            }
        ],
        listeners: [
            {
                fn: 'onLstLinksItemTap',
                event: 'itemtap',
                delegate: '#lstViewLinks'
            }
        ]
    },

    onLstLinksItemTap: function(dataview, index, target, record, e, eOpts) {

        //            Ext.Global.RedirectToView(record.data);


        window.open( Ext.Global.GetConfig('CMSWSUrl') + '/TradeExchange/GetReportFile?id=' + record.data.id + '&culture=' + Ext.Global.LanguageFlag ,'_system');



    },

    initialize: function() {
        Ext.Localization.LocalizeView(this);

        //var links = Ext.Localization.getLinks(this);


                var view = this;
                Ext.Localization.LocalizeView(view);

                var ajaxAndPagingParams = {
                    list: view.down('#lstViewLinks'),
                    moreText: Ext.Localization.GetMessage('LoadMore'),
                    noRecords: Ext.Localization.GetMessage('NoMoreInfo'),
                    url: Ext.Global.GetConfig('CMSWSUrl')+ '/TradeExchange/GetAllReports?culture='+Ext.Global.LanguageFlag,
                    pageSize: 10
                };

                Ext.Global.LoadAjaxWithPaging(ajaxAndPagingParams);



        this.callParent();
    }

});