/*
 * File: app/view/TradeActivityAvailabilityView.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MEC_App.view.TradeActivityAvailabilityView', {
    extend: 'Ext.form.Panel',
    alias: 'widget.TradeActivityAvailabilityView',

    requires: [
        'Ext.Label',
        'Ext.form.FieldSet',
        'Ext.field.Text',
        'Ext.Button',
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        cls: 'complaint-view',
        itemId: 'tradenameavailabilityview1',
        layout: 'fit',
        scrollable: false,
        items: [
            {
                xtype: 'label',
                cls: 'inners-title',
                docked: 'top',
                html: 'البحث عن نشاط تجاري',
                itemId: 'lblTitle'
            },
            {
                xtype: 'fieldset',
                docked: 'top',
                items: [
                    {
                        xtype: 'textfield',
                        id: 'txtActivity',
                        label: 'اسم النشاط',
                        name: 'txtActivity',
                        placeHolder: 'اسم النشاط'
                    },
                    {
                        xtype: 'button',
                        cls: 'btn-send',
                        itemId: 'btnSubmitActivity',
                        text: 'بحث'
                    }
                ]
            },
            {
                xtype: 'list',
                cls: 'CompanyList',
                height: '100%',
                id: 'lstTradeActivityResults',
                itemId: 'lstTradeActivityResults',
                itemCls: 'item-activity',
                itemTpl: [
                    '<div class=\'tpl-activity-1\'>{businessActivityArabicName}</div>',
                    '<div class=\'tpl-activity-2\'>{fees} ر.ق</div>'
                ]
            }
        ]
    }

});