/*
 * File: app/view/ViolationsDetailsView.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MEC_App.view.ViolationsDetailsView', {
    extend: 'Ext.Panel',
    alias: 'widget.ViolationsDetailsView',

    requires: [
        'Ext.Label',
        'Ext.Img',
        'Ext.Panel'
    ],

    config: {
        cls: 'rtl',
        itemId: 'ViolationsDetailsView',
        layout: 'vbox',
        scrollable: 'vertical',
        items: [
            {
                xtype: 'label',
                cls: 'inners-title',
                html: 'إغلاق إداري',
                itemId: 'lblTitle'
            },
            {
                xtype: 'image',
                cls: 'img',
                height: 201,
                itemId: 'imgDetails'
            },
            {
                xtype: 'panel',
                cls: 'text-panel',
                itemId: 'pnl1',
                items: [
                    {
                        xtype: 'label',
                        cls: 'violation-label-1',
                        html: 'المحل المخالف',
                        itemId: 'lbl1'
                    },
                    {
                        xtype: 'label',
                        cls: 'text-container2',
                        itemId: 'lblCompanyName'
                    }
                ]
            },
            {
                xtype: 'panel',
                cls: 'text-panel',
                itemId: 'pnl2',
                items: [
                    {
                        xtype: 'label',
                        cls: 'violation-label-2',
                        html: 'المخالفة',
                        itemId: 'lbl2'
                    },
                    {
                        xtype: 'label',
                        cls: 'text-container2',
                        itemId: 'lblViolation'
                    }
                ]
            },
            {
                xtype: 'panel',
                cls: 'text-panel',
                itemId: 'pnl3',
                items: [
                    {
                        xtype: 'label',
                        cls: 'violation-label-3',
                        html: 'العقوبة',
                        itemId: 'lbl3'
                    },
                    {
                        xtype: 'label',
                        cls: 'text-container2',
                        itemId: 'lblPunishment'
                    }
                ]
            },
            {
                xtype: 'panel',
                cls: 'text-panel',
                itemId: 'pnl4',
                items: [
                    {
                        xtype: 'label',
                        cls: 'violation-label-4',
                        html: 'رقم القرار',
                        itemId: 'lbl4'
                    },
                    {
                        xtype: 'label',
                        cls: 'text-container2',
                        itemId: 'lblDecisionNumber'
                    }
                ]
            }
        ]
    }

});