/*
 * File: app/view/WhereToShopView.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MEC_App.view.WhereToShopView', {
    extend: 'Ext.Panel',
    alias: 'widget.WhereToShopView',

    requires: [
        'Ext.Label',
        'Ext.dataview.List',
        'Ext.Panel',
        'Ext.field.Hidden',
        'Ext.XTemplate'
    ],

    config: {
        id: 'WhereToShopView',
        itemId: 'WhereToShopView',
        layout: 'vbox',
        scrollable: false,
        cls: [
            'complaint-view',
            'rtl'
        ],
        items: [
            {
                xtype: 'label',
                cls: 'inners-title',
                docked: 'top',
                html: 'أين تتسوق'
            },
            {
                xtype: 'textfield',
                docked: 'top',
                itemId: 'txtProductName',
                label: 'اختر منتج',
                placeHolder: 'اختر منتج',
                readOnly: true,
                listeners: [
                    {
                        fn: function(component, eOpts) {

                            // Create Native drop down
                            var me = this;
                            me.element.on('tap', function(){

                                var data = me.up('WhereToShopView').getData();


                                var items = [];

                                Ext.each(data, function(item){
                                    items.push({ text: item.ProductName, value: item.Id});
                                });


                                var btn = this;
                                var config = {
                                    title: "المنتج",
                                    items: items,
                                    //selectedValue: "2",
                                    doneButtonLabel: "اختيار",
                                    cancelButtonLabel: "الغاء"
                                };


                                var hiddenProductID = Ext.ComponentQuery.query("#hiddenProductID")[0];

                                Ext.DeviceController.ShowNativePickerWithValue(me, hiddenProductID,config);


                            }, me);

                        },
                        event: 'initialize'
                    }
                ]
            },
            {
                xtype: 'list',
                itemId: 'lstPrices',
                itemCls: 'grid-row',
                itemTpl: [
                    '',
                    '    <div class=\'row-cell\'>{Shop.ShopName}</div>    ',
                    '    <div class=\'row-cell\'>{Quantity}({Unit.Name})</div>    ',
                    '    <div class=\'row-cell\'>{Price}</div>    ',
                    '',
                    ''
                ],
                items: [
                    {
                        xtype: 'panel',
                        cls: 'grid-header',
                        docked: 'top',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'label',
                                flex: 1,
                                cls: 'header-cell1',
                                html: 'اسم المحل'
                            },
                            {
                                xtype: 'label',
                                flex: 1,
                                cls: 'header-cell2',
                                html: 'الكمية'
                            },
                            {
                                xtype: 'label',
                                flex: 1,
                                cls: 'header-cell2',
                                html: 'السعر'
                            }
                        ]
                    },
                    {
                        xtype: 'hiddenfield',
                        itemId: 'hiddenProductID'
                    }
                ]
            }
        ]
    }

});