/*
 * File: app/controller/InvestorEducationController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MEC_App.controller.InvestorEducationController', {
    extend: 'Ext.app.Controller',
    alias: 'controller.InvestorEducationController',

    config: {
        control: {
            "panel#InvestorEducationView": {
                initialize: 'onInvestorEducationViewInitialize'
            }
        }
    },

    onInvestorEducationViewInitialize: function(component, eOpts) {
        var view = component;//me.getMyBusinessView();
        Ext.Localization.LocalizeView(view);

        Ext.AnimationHelper.ShowLoading();


        var me = this;

        Ext.Ajax.request({

            url : Ext.Global.GetConfig('CMSWSUrl')+ '/InvestorEducation/GetAllInvestorEducations?culture='+Ext.Global.LanguageFlag+'&pageSize=20&pageIndex=0',
            method : 'Get',
            success : function (response) {

                var json = Ext.util.JSON.decode(response.responseText);

                console.log(json);


                var store = new Ext.data.Store({
                    data : json
                });

                var lstEducation = view.down('#lstEducation');
                lstEducation.setStore(store);

                Ext.AnimationHelper.HideLoading();
            }
        });


    }

});