/*
 * File: app/controller/LocAr.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MEC_App.controller.LocAr', {
    extend: 'Ext.Base',

    config: {
    },

    Load: function(g) {
        g.ViewTitles = {

            'Home': 'الرئيسية',
            'PublicServices':'الخدمات العامة',
            'MediaCenter': ' المركز الاعلامي',
            'Inquiries': 'الاستعلامات والاصدارات ',
            'ContactUs': 'اتصل بنا',
            'Projects' : 'المبادرات والمشاريع',
            'Reports': 'المؤشرات والتقارير',
            'Settings': 'الاعدادات',
            'LogivForm' : 'تسجيل الدخول',

            //media center



            'MinistryPublications' : 'اصدارات الوزارة',
            'MinistryNews' : 'اصداء عن الوزارة',
            'EconomyNews' : 'اخبار اقتصادية',


            //services

            'PrintOffs' :' خدمات المستخرجات',
            'MyBusiness' :' بياناتي الخاصة',
            'RequestFollowup' :' متابعة المعاملات',
            'Complaints' :' ابلاغ عن شكوي',
            'SupplyService' :' خدمات التموين',
            'InvestorServices' :' خدمات المستثمر',
            'ConsumerServices' :' خدمات المستهلك',




            // inq

            'SearchTradeName' :    'البحث عن اسم تجاري',
            'SearchAct' :'البحث عن نشاط تجاري',
            'Recalls' :'الاستدعاءات',
            'ConsulerEdu' :'ثقافة المستهلك',
            'InvestorEdu' :'ثقافة المستثمر',
            'Violations' :'المخالفات والاغلاقات',



            //reports



            'EcoReports' :'مؤشرات اقتصادية',
            'BizReports' :'مؤشرات الاعمال',
            'ConsumerReports' :'مؤشرات استهلاكية',
            'TradeReports' :'تقرير العلامات التجارية',


            //contact

            'AboutMinistry' :'عن الوزارة',
            'Branches' :'الفروع',
            'Suggestions' :'مقترحات',
            'ContactUs2' :'تواصل معنا',
            'Employees' :'موظفو الوزارة'





        };



        g.GenericContent ={

            HomeNews:'<div class="header-text-bg"><b>اخبار عامّة اخبار عامّة اخبار عامّة</b><br />اخبار عامّة اخبار عامّة  </div>'
        };








    }

});