/*
 * File: app/controller/LocAr.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MEC_App.controller.LocAr', {
    extend: 'Ext.Base',

    config: {
    },

    Load: function(g) {
        g.ViewTitles = {

            Home: "الرئيسية",
            PublicServices:"الخدمات العامة",
            MediaCenter: " المركز الاعلامي",
            Inquiries: "الاستعلامات والاصدارات ",
            ContactUs: "التواصل",
            Projects : "المبادرات والمشاريع",
            Reports: "المؤشرات والتقارير",
            Settings: "الاعدادات",
            LogivForm : "تسجيل الدخول",

            //media center

            MinistryPublications : 'اصدارات الوزارة',
            MinistryNews  : 'اخبار الوزارة',
            EconomyNews : 'اخبار الوزارة',
            NewsDetails : 'تفاصيل الخبر',

            MinistryReflections  : 'انعكاسات',
            MinistryNewsSection3 : 'اخبار جهات رسمية اقليمية مشابهة',
            MinistryNewsSection4 : 'اخبار اقتصادية اقليمية',
            MinistryNewsSection5 : 'اخبار جهات رسمية دولية مشابهة',
            MinistryNewsSection6 : 'اخبار اقتصادية دولية',






            //services

            PrintOffs :' خدمات المستخرجات',
            MyBusiness :' بياناتي الخاصة',
            RequestFollowup :' متابعة المعاملات',
            Complaints :' ابلاغ عن شكوى',
            SupplyService :' خدمات التموين',
            InvestorServices :' خدمات المستثمر',
            ConsumerServices :' خدمات المستهلك',




            // inq

            SearchTradeName :    'البحث عن اسم تجاري',
            SearchAct :'البحث عن نشاط تجاري',
            Recalls :'الاستدعاءات',
            ConsulerEdu :'ثقافة المستهلك',
            InvestorEdu :'ثقافة المستثمر',
            Violations :'المخالفات والاغلاقات',



            //reports



            EcoReports :'مؤشرات اقتصادية',
            BizReports :'مؤشرات الاعمال',
            ConsumerReports :'مؤشرات استهلاكية',
            TradeReports :'تقرير العلامات التجارية',


            //contact

            AboutMinistry :'عن الوزارة',
            Branches :'الفروع',
            Suggestions :'مقترحات',
            ContactUs2 :'تواصل معنا',
            Employees :'موظفو الوزارة'

        };


        g.ComplaintsLabels ={

            shopName: 'اسم المتجر',
            shopLocation: ' موقع المتجر',
            ComplaintType: ' نوع الشكوى',
            txtComplaint: ' نص الشكوى',
            fullName: ' الاسم بالكامل',
            email: ' البريد الالكتدوني',
            mobile: ' رقم الهاتف',
            barcode:  'باركود المنتج',
            AttachImg: ' ارفق صور المنتج',
            Submit: 'ارسل'

        };



        g.ValidationMsg ={

            errShopName:'فضلا ادخل اسم المتجر\n',
            errComplaintType:'فضلا اختر نوع الشكوي\n',
            errComplaintText:'فضلا ادخل نص الشكوي\n',
            errFullName:'فضلا ادخل الاسم بالكامل\n',
            errMobile:'فضلا ادخل رقم الجوال\n',
            errUserName:'فضلا ادخل اسم المستخدم\n',
            errPassword:'فضلا ادخل كلمة السر\n',
            errSuggestion : 'فضلا ادخل المقترح\n'
        };


        g.ConfirmationMsg ={

            msgConfirmComplaints:'تم ارسال الشكوي بنجاح'



        };



        g.GenericContent ={

            HomeNews:'<div class="header-text-bg">اخبار عامّة اخبار عامّة اخبار عامّة<br />اخبار عامّة اخبار عامّة  </div>'
        };











    }

});