/*
 * File: app/controller/MinistryNewsController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MEC_App.controller.MinistryNewsController', {
    extend: 'Ext.app.Controller',

    config: {
        control: {
            "list#lstNews": {
                itemtap: 'onLstNewsItemTap'
            }
        }
    },

    onLstNewsItemTap: function(dataview, index, target, record, e, eOpts) {

                    //alert(record.data.NewsDate);

               dataview.up('MainNavView').push({
                    xtype: 'NewsDetailsView',
                    title: Ext.Global.GetViewTitle('NewsDetails'),
                   Data: record.data

                });





    }

});