/*
 * File: app/controller/PrintOffsController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MEC_App.controller.PrintOffsController', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            PrintOffsView1: '#PrintOffsView1',
            PrintOffsView2: '#PrintOffsView2'
        },

        control: {
            "button#btnPrintoffsNext": {
                tap: 'onBtnPrintoffsNextTap'
            },
            "panel#PrintOffsView2": {
                initialize: 'onPrintOffsView2Initialize'
            },
            "button#btnPrintoffs2Next": {
                tap: 'onBtnPrintoffs2NextTap'
            },
            "panel#PrintOffsView3": {
                initialize: 'onPrintOffsView3Initialize'
            },
            "formpanel#PrintOffsView1": {
                initialize: 'onPrintOffsView1Initialize'
            }
        }
    },

    onBtnPrintoffsNextTap: function(button, e, eOpts) {

        // Create Case with Form Values


        var view = this.getPrintOffsView1();

        Ext.AnimationHelper.ShowLoading();

        var requestData = {
            "serviceId": "9",
            "token": Ext.Global.userToken,
            "language": "ar",
            "identityType": 'QID',//Ext.Global.identityType,
            "identityNum": Ext.Global.identityNum,
            "identityNationality": Ext.Global.identityNationality,
            "commercialRegistrationNum":view.down('#hiddenCompanyCR').getValue(),
            "caseType":view.down('#hiddenPrintoutType').getValue(),
            "establishmentSpcId":"",
            "caseSubType":"01",
            "contactId":"",
            "numOfCopies":view.down('#txtNoOfCopies').getValue(),
            "moiEstablishmentNum":"",
            "qatarChamberNum":"",
            "commercialPermitNum":"",
            "economicalNum":""
        };



        Ext.Ajax.request({

            url : Ext.Global.GetConfig('webServiceUrl'),
            method : 'POST',
            jsonData :requestData,
            success : function (response) {
                var json = Ext.util.JSON.decode(response.responseText);

                //console.log(json);
                Ext.Viewport.getActiveItem().push({
                    xtype: 'PrintOffsView2',
                    title: Ext.Global.GetFixedTitle(),
                    data: json
                });


                Ext.AnimationHelper.HideLoading();


            }
        });













    },

    onPrintOffsView2Initialize: function(component, eOpts) {
                 var view = this.getPrintOffsView2();
                var json = view.getData();

        view.down('#lblRequestType').setHtml(json.listOfMecBssCreatedCaseIo.mecLlcEstablishment[0].type);
        view.down('#lblNoCopies').setHtml('');
        view.down('#lblCompanyName').setHtml(json.listOfMecBssCreatedCaseIo.mecLlcEstablishment[0].orgNameARA);
        view.down('#lblTotalFees').setHtml(json.listOfMecBssCreatedCaseIo.mecLlcEstablishment[0].listOfMecCaseFees.mecCaseFees[0].feesTotalValue);


        view.down('#lblRequestNo').setHtml(json.listOfMecBssCreatedCaseIo.mecLlcEstablishment[0].serialNumber);
        view.down('#hiddenSerialNo').setValue(json.listOfMecBssCreatedCaseIo.mecLlcEstablishment[0].recordID);

        view.down('#lblRequestStatus').setHtml(json.listOfMecBssCreatedCaseIo.mecLlcEstablishment[0].status);

        var noOfAttachments = json.listOfMecBssCreatedCaseIo.mecLlcEstablishment[0].listOfMecUnifiedAttachmentParameters.mecUnifiedAttachmentParameters.length;

        if(noOfAttachments===0){
            view.down('#lblRequiredAttachments').setHtml('لا يوجد');
            }





    },

    onBtnPrintoffs2NextTap: function(button, e, eOpts) {
                 Ext.AnimationHelper.ShowLoading();

                         var view = this.getPrintOffsView2();
                         var serialNo =  view.down('#hiddenSerialNo').getValue();


        console.log(serialNo);

        var formData = view.getData();




                        var requestData = {
          "serviceId": "10",
          "token": Ext.Global.userToken,
          "objectSpcId": serialNo,
          "caseSerialNum":""
        };


                        Ext.Ajax.request({

                            url : Ext.Global.GetConfig('webServiceUrl'),
                            method : 'POST',
                            jsonData :requestData,
                            success : function (response) {
                               var json = Ext.util.JSON.decode(response.responseText);




                                Ext.AnimationHelper.HideLoading();


                                if(json.statusMsg!='success')
                                {

                                    var company = formData.listOfMecBssCreatedCaseIo.mecLlcEstablishment[0];
                                    json.recordID = company.caseNum;
                                    json.typeCode = company.typeCode;
                                    json.fees = company.listOfMecCaseFees.mecCaseFees[0].feesTotalValue;
                                    json.locale = 'ar';




                                    Ext.Viewport.getActiveItem().push({
                                    xtype: 'PrintOffsView3',
                                    title: Ext.Global.GetFixedTitle(),
                                    data: json
                                    });
                                }else{


                                Ext.device.Notification.show({
                                    title: 'خطأ',
                                    buttons: ["موافق"],
                                    message:  'json.statusMsg'
                                    });

                                }



                            }
                        });





    },

    onPrintOffsView3Initialize: function(component, eOpts) {
        var view = component;
        var data = view.getData();

        console.log(data);

         Ext.Function.defer(function(){
        // payment gateway redirection

                var form = Ext.create('Ext.form.Panel', {
                        standardSubmit: true,
                        url: 'http://eservicesstg.mec.gov.qa/QNB_PaymentGateway/CS_VPC_3Party_DO_mob.aspx',
                        method: 'POST',
                    items: [
                        {xtype: 'textfield',name: 'vpc_MerchTxnRef'},
                        {xtype: 'textfield',name: 'vpc_OrderInfo'},
                        {xtype: 'textfield',name: 'vpc_Amount'},
                        {xtype: 'textfield',name: 'vpc_Locale'}
                    ],
                    });


                form.setValues({
                            vpc_MerchTxnRef: data.recordID, //'Ahmed Adly Ali',
                            vpc_OrderInfo: data.caseSerialNum + '_' + data.typeCode,//'Test',
                            vpc_Amount: data.fees,
                            vpc_Locale : data.locale

                        });

                form.element.dom.target = 'paymentframe';
                form.submit(); //{target: 'paymentframe'}


         } ,	400,this);
    },

    onPrintOffsView1Initialize: function(component, eOpts) {
        Ext.AnimationHelper.ShowLoading();


        var requestData = {
            "serviceId": "2",
            "token": Ext.Global.userToken,
            "language": "ar",
            "identityType":'QID', //Ext.Global.identityType,
            "identityNum": Ext.Global.identityNum,
            "identityNationality":  Ext.Global.identityNationality
        };


        var me = this;

        Ext.Ajax.request({

            url : Ext.Global.GetConfig('webServiceUrl'),
            method : 'POST',
            jsonData :requestData,
            success : function (response) {

                var json = Ext.util.JSON.decode(response.responseText);


                var view = me.getPrintOffsView1();

                view.setData(json.listOfPrimaryEstablishment.primaryEstablishment);

                Ext.AnimationHelper.HideLoading();




            }
        });

    }

});