/*
 * File: app/controller/PrintOffsController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MEC_App.controller.PrintOffsController', {
    extend: 'Ext.app.Controller',

    requires: [
        'MEC_App.view.PrintOffsView1'
    ],

    config: {
        refs: {
            PrintOffsView1: 'PrintOffsView1',
            PrintOffsView2: 'PrintOffsView2'
        },

        control: {
            "button#btnPrintoffsNext": {
                tap: 'onBtnPrintoffsNextTap'
            },
            "panel#PrintOffsView2": {
                initialize: 'onPrintOffsView2Initialize',
                show: 'onPrintOffsView2Show'
            },
            "button#btnPrintoffs2Next": {
                tap: 'onBtnPrintoffs2NextTap'
            },
            "panel#PrintOffsView3": {
                initialize: 'onPrintOffsView3Initialize'
            },
            "formpanel#PrintOffsView1": {
                initialize: 'onPrintOffsView1Initialize'
            }
        }
    },

    onBtnPrintoffsNextTap: function(button, e, eOpts) {

    },

    onPrintOffsView2Initialize: function(component, eOpts) {

    },

    onPrintOffsView2Show: function(component, eOpts) {

    },

    onBtnPrintoffs2NextTap: function(button, e, eOpts) {

    },

    onPrintOffsView3Initialize: function(component, eOpts) {

    },

    onPrintOffsView1Initialize: function(component, eOpts) {

    }

});