/*
 * File: app/controller/PublicServicesController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MEC_App.controller.PublicServicesController', {
    extend: 'Ext.app.Controller',

    config: {
        control: {
            "button#printOfficeBtn": {
                tap: 'onPrintOfficeBtnTap'
            },
            "button#myServiceBtn": {
                tap: 'onMyServiceBtnTap'
            },
            "button#myRequestsBtn": {
                tap: 'onMyRequestsBtnTap'
            },
            "button#complainsBtn": {
                tap: 'onComplainsBtnTap'
            },
            "button#supplyServicesBtn": {
                tap: 'onSupplyServicesBtnTap'
            },
            "button#adminServiceBtn": {
                tap: 'onAdminServiceBtnTap',
                tap: 'onAdminServiceBtnTap'
            },
            "panel#AdminServicesView": {
                initialize: 'onAdminServicesViewInitialize'
            },
            "list#lstLinks": {
                itemtap: 'onLstLinksItemTap'
            }
        }
    },

    onPrintOfficeBtnTap: function(button, e, eOpts) {

              Ext.Global.RedirectLoggedUser('PrintOffsView1');








    },

    onMyServiceBtnTap: function(button, e, eOpts) {
                 Ext.Global.RedirectLoggedUser('MyBusinessView');

    },

    onMyRequestsBtnTap: function(button, e, eOpts) {
                        Ext.Global.RedirectLoggedUser('MyRequestsView');

    },

    onComplainsBtnTap: function(button, e, eOpts) {
        button.up('MainNavView').push({
                    xtype: 'ComplaintsView',
                    title: Ext.Global.GetFixedTitle()
                });
    },

    onSupplyServicesBtnTap: function(button, e, eOpts) {
        Ext.Global.RedirectLoggedUser('SupplyServiceView1');

        //button.up('MainNavView').push({
        //                 xtype: 'SupplyServiceView1',
        //               title: Ext.Global.GetFixedTitle()
        //         });

    },

    onAdminServiceBtnTap: function(button, e, eOpts) {

    },

    onAdminServiceBtnTap: function(button, e, eOpts) {
                //Ext.Global.RedirectLoggedUser('AdminServicesView');


                button.up('MainNavView').push({
                                 xtype: 'AdminServicesView',
                               title: Ext.Global.GetFixedTitle()
                         });
    },

    onAdminServicesViewInitialize: function(component, eOpts) {
        var view = component;

        var links = [{Name:'تجديد السجل التجاري',Url:'http://eservicesstg.mec.gov.qa/eservice_ara/start.swe?SWECmd=GotoView&SWEView=MEC+Renewal+General+Instructions+View+eService'},
                     {Name:'تجديد الرخصة التجارية',Url:'http://eservicesstg.mec.gov.qa/eservice_ara/start.swe?SWECmd=GotoView&SWEView=MEC+CP+Renew+General+Instructions+View+eService'},
                     {Name:'تغيير الإسم التجارى',Url:'http://eservicesstg.mec.gov.qa/eservice_ara/start.swe?SWECmd=GotoView&SWEView=MEC+Change+Services+General+Instructions+View+eService'},
                     {Name:'تغيير المدراء (المخولين بالتوقيع)',Url:'http://eservicesstg.mec.gov.qa/eservice_ara/start.swe?SWECmd=GotoView&SWEView=MEC+Change+Services+General+Instructions+View+eService'},
                     {Name:'محو فرع',Url:'http://eservicesstg.mec.gov.qa/eservice_ara/start.swe?SWECmd=GotoView&SWEView=MEC+Delete+CR+General+Instructions+View+eService'},
                     {Name:'محو سجل رئيسي',Url:'http://eservicesstg.mec.gov.qa/eservice_ara/start.swe?SWECmd=GotoView&SWEView=MEC+Delete+CR+General+Instructions+View+eService'}

                    ];

        var store = new Ext.data.Store({
                            data : links
                        });

                var lst = view.down('#lstLinks');
                lst.setStore(store);


    },

    onLstLinksItemTap: function(dataview, index, target, record, e, eOpts) {
        Ext.Viewport.getActiveItem().push({
            xtype: 'WebFrameView',
            title: Ext.Global.GetFixedTitle(),
            data: record.data
        });

    }

});