/*
 * File: app/controller/RecallsController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MEC_App.controller.RecallsController', {
    extend: 'Ext.app.Controller',

    config: {
        control: {
            "panel#RecallsView": {
                initialize: 'onRecallsViewInitialize'
            },
            "panel#RecallDetailsView": {
                initialize: 'onRecallDetailsViewInitialize'
            },
            "list#lstRecalls": {
                itemtap: 'onLstRecallsItemTap'
            }
        }
    },

    onRecallsViewInitialize: function(component, eOpts) {

        var view = component;
        Ext.Localization.LocalizeView(view);

        var ajaxAndPagingParams = {
            list: view.down('#lstRecalls'),
            moreText: Ext.Localization.GetMessage('LoadMore'),
            noRecords: Ext.Localization.GetMessage('NoMoreInfo'),
            url: Ext.Global.GetConfig('CMSWSUrl')+ '/Recall/GetAllRecalls?culture='+Ext.Global.LanguageFlag,
            pageSize: 10
        };

        Ext.Global.LoadAjaxWithPaging(ajaxAndPagingParams);

    },

    onRecallDetailsViewInitialize: function(component, eOpts) {
        Ext.Localization.LocalizeView(component);

        var view = component;
        var data = view.getData();


        view.down('#lblTitle').setHtml(data.ProductTitle);
        view.down('#lblDetails').setHtml(data.ProductIssue);
        view.down('#lblProdcedure').setHtml(data.ConsumerProcedure);
        view.down('#imgDetails').setSrc(Ext.Global.GetConfig('CMSWSUrl')+"/Recall/Image/"+data.Id);


        var contact = data.ContactSupplier;


        var tel = data.ContactTel ? '<a href=tel:'+data.ContactTel+'>'+data.ContactTel+'</a>' : '';
        var email = data.ContactEmail ? '<a href=mailto:'+data.ContactEmail+'>'+data.ContactEmail+'</a>' : '';


        if(data.ContactTel)
        contact = contact + '<br>' + tel;

        if(data.ContactEmail)
        contact = contact + ' - ' + email;

        //console.log(data);


        view.down('#lblContact').setHtml(contact);



    },

    onLstRecallsItemTap: function(dataview, index, target, record, e, eOpts) {
        dataview.up('MainNavView').push({
            xtype: 'RecallDetailsView',
            title: Ext.Global.GetFixedTitle(),
            data: record.data

        });
    }

});