/*
 * File: app/controller/RecallsController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MEC_App.controller.RecallsController', {
    extend: 'Ext.app.Controller',

    config: {
        control: {
            "panel#RecallsView": {
                initialize: 'onRecallsViewInitialize'
            },
            "panel#RecallDetailsView": {
                initialize: 'onRecallDetailsViewInitialize'
            },
            "list#lstRecalls": {
                itemtap: 'onLstRecallsItemTap'
            }
        }
    },

    onRecallsViewInitialize: function(component, eOpts) {
        Ext.Localization.LocalizeView(component);

        var view = component;//me.getMyBusinessView();


        Ext.AnimationHelper.ShowLoading();




        var me = this;

        Ext.Ajax.request({

            url : Ext.Global.GetConfig('CMSWSUrl')+ '/Recall/GetAllRecalls?culture='+Ext.Global.LanguageFlag+'&pageSize=20&pageIndex=0',
            method : 'Get',
            success : function (response) {

                var json = Ext.util.JSON.decode(response.responseText);

                console.log(json);


                var store = new Ext.data.Store({
                    data : json
                });

                var lstRecalls = view.down('#lstRecalls');
                lstRecalls.setStore(store);

                Ext.AnimationHelper.HideLoading();
            }
        });

    },

    onRecallDetailsViewInitialize: function(component, eOpts) {
        Ext.Localization.LocalizeView(component);

        var view = component;
        var data = view.getData();


        view.down('#lblTitle').setHtml(data.ProductTitle);
        view.down('#lblDetails').setHtml(data.ProductIssue);
        view.down('#lblProdcedure').setHtml(data.ConsumerProcedure);
        view.down('#lblContact').setHtml(data.ContactSupplier);
        view.down('#imgDetails')
        .setSrc(Ext.Global.GetConfig('CMSWSUrl')+"/Recall/Image/"+data.Id);







    },

    onLstRecallsItemTap: function(dataview, index, target, record, e, eOpts) {
        dataview.up('MainNavView').push({
            xtype: 'RecallDetailsView',
            title: Ext.Global.GetFixedTitle(),
            data: record.data

        });
    }

});