/*
 * File: app/controller/ReportsController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MEC_App.controller.ReportsController', {
    extend: 'Ext.app.Controller',

    config: {
        control: {
            "button#reportsBtn1": {
                tap: 'onReportsBtn1Tap'
            },
            "button#reportsBtn2": {
                tap: 'onReportsBtn2Tap'
            },
            "button#reportsBtn3": {
                tap: 'onReportsBtn3Tap'
            },
            "button#reportsBtn4": {
                tap: 'onReportsBtn4Tap'
            }
        }
    },

    onReportsBtn1Tap: function(button, e, eOpts) {
        button.up('MainNavView').push({
                    xtype: 'EconomicIndicatorsListing',
                    title: Ext.Global.GetFixedTitle()
                });


    },

    onReportsBtn2Tap: function(button, e, eOpts) {
        button.up('MainNavView').push({
                    xtype: 'BusinessIndicatorsView',
                    title: Ext.Global.GetFixedTitle()
                });
    },

    onReportsBtn3Tap: function(button, e, eOpts) {
        button.up('MainNavView').push({
                    xtype: 'ConsumerIndicatorsView',
                    title: Ext.Global.GetFixedTitle()
                });
    },

    onReportsBtn4Tap: function(button, e, eOpts) {
        button.up('MainNavView').push({
                    xtype: 'BusinessIndicatorsReport',
                    title: Ext.Global.GetFixedTitle()
                });
    }

});