/*
 * File: app/controller/SettingsViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MEC_App.controller.SettingsViewController', {
    extend: 'Ext.app.Controller',
    alias: 'controller.SettingsViewController',

    config: {
        control: {
            "segmentedbutton#languageButtons": {
                initialize: 'onLanguageButtonsInitialize'
            }
        }
    },

    onLanguageButtonsInitialize: function(component, eOpts) {

        if(Ext.Global.LanguageFlag == 'en') {
            component.setPressedButtons([0]);
        }
        else {
            component.setPressedButtons([1]);
        }
    }

});