/*
 * File: app/controller/TradeNameAvailabilityController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MEC_App.controller.TradeNameAvailabilityController', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            txtActivityName: '#txtActivityName',
            lstResults: '#lstResults'
        },

        control: {
            "button#btnSubmit": {
                tap: 'onBtnSubmitTap'
            },
            "list#lstTradeNameResults": {
                itemtap: 'onLstTradeNameResultsItemTap'
            }
        }
    },

    onBtnSubmitTap: function(button, e, eOpts) {

        Ext.Viewport.setMasked({
                xtype: 'loadmask',
                message: 'جاري التحم...'
            });


        Ext.Ajax.request({

            url : 'http://webservicesstg.mec.gov.qa/MECBSSGateway/mecbssgw/bssgateway/accept',
            method : 'POST',
            // useDefaultXhrHeader: false,
            jsonData :
            {"serviceId":"5",
             "language":"ARA",
             "englishSearchClause":"",
             "arabicSearchClause":this.getTxtActivityName().getValue()
            },
            success : function (response) {
                var json = Ext.util.JSON.decode(response.responseText);


           var store = new Ext.data.Store({
                        //model: 'MEC_App.model.TradeNameResultModel',
                        data : json.listOfMecBusinessActivitiesIo.mecBusinessActivitiesIo
                        });


            var lst = Ext.getCmp('lstTradeNameResults');
            lst.setStore(store);


              Ext.Viewport.setMasked(false); // hide the load screen


            },
            failure: function(request, resp) {
                alert("in failure");
            }
        });



    },

    onLstTradeNameResultsItemTap: function(dataview, index, target, record, e, eOpts) {

        dataview.up('MainNavView').push({
            xtype: 'TradeNameEstablishmentDetails',
            title: 'تفاصيل الشركة',
            data: record.data

        });





    }

});